name: CI/CD to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: brilliant-dock-482112-t7
  PROJECT_NUMBER: 811562434244
  REGION: us-central1
  CLUSTER: gke-cicd-cluster
  REPOSITORY: node-repo
  IMAGE: node-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build \
        -t $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest .

    - name: Push Docker image
      run: |
        docker push \
        $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials \
        $CLUSTER \
        --region $REGION \
        --project $PROJECT_ID

    - name: Deploy to GKE
      run: kubectl apply -f k8s/
