apiVersion: v1
kind: Service
metadata:
  name: gke-cicd-app-service
spec:
  type: LoadBalancer
  selector:
    app: gke-cicd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
